### ISSUE TITLE
Tests don't pass

### ISSUE THREAD

**Issue by mikbry** [Zoapp/core#20]
yarn test

● database/mysql/mysqlTable › moveItems › reorders rows

    expect(received).toEqual(expected)
    
    Expected value to equal:
      ["it-1", "it-2", "it-3", "it-4"]
    Received:
      ["it-1"]
    
    Difference:
    
    - Expected
    + Received
    
      Array [
        "it-1",
    -   "it-2",
    -   "it-3",
    -   "it-4",
      ]

      57 | 
      58 |       let items = await table1.getItems();
    > 59 |       expect(items.map((i) => i.id)).toEqual(["it-1", "it-2", "it-3", "it-4"]);
      60 |       expect(items.map((i) => i.order)).toEqual([1, 2, 3, 4]);
      61 | 
      62 |       // move first item at the third position
      
      at Object.it (tests/database/mysql/mysqlTable.test.js:59:38)

  ● database/mysql/mysqlTable › getItems › get items ordered

    expect(received).toEqual(expected)
    
    Expected value to equal:
      ["it-2", "it-3", "it-1"]
    Received:
      ["it-3"]
    
    Difference:
    
    - Expected
    + Received
    
      Array [
    -   "it-2",
        "it-3",
    -   "it-1",
      ]

      186 | 
      187 |       const items = await table1.getItems();
    > 188 |       expect(items.map((i) => i.id)).toEqual(["it-2", "it-3", "it-1"]);
      189 |     });
      190 |   });
      191 | 
      
      at Object.it (tests/database/mysql/mysqlTable.test.js:188:38)

  ● database/mysql/mysqlTable › size › returns the number of results restricted by a WHERE clause

    expect(received).toEqual(expected)
    
    Expected value to equal:
      1
    Received:
      0

      231 |       });
      232 |       let count = await table1.size("name='it-1'");
    > 233 |       expect(count).toEqual(1);
      234 |       count = await table1.size("name='it-0'");
      235 |       expect(count).toEqual(0);
      236 |     });
      
      at Object.it (tests/database/mysql/mysqlTable.test.js:233:21)

**Comment by mikbry** [comment]
Seems there is duplicate primary key. UUID collision

**Comment by willdurand** [comment]
I cannot reproduce locally or on travis ci :/

**Comment by mikbry** [comment]
Was a forEach async mess :-)
